/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.PopupMenu;
import javax.swing.JDesktopPane;
import services.EtudiantService;

/**
 *
 * @author Hp
 */
public class MDIApplication extends javax.swing.JFrame {

    private PopupMenu ebn;

    /**
     * Creates new form MDIApplication
     */
    public MDIApplication() {
        initComponents();
        this.setTitle("TP Organizer");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        acceuilMenu = new javax.swing.JMenu();
        nbtTP = new javax.swing.JMenuItem();
        EtudiantMenuItem = new javax.swing.JMenuItem();
        participationMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        acceuilMenu.setMnemonic('f');
        acceuilMenu.setText("Acceuil");

        nbtTP.setMnemonic('o');
        nbtTP.setText("tp");
        nbtTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbtTPActionPerformed(evt);
            }
        });
        acceuilMenu.add(nbtTP);

        EtudiantMenuItem.setMnemonic('s');
        EtudiantMenuItem.setText("Etudiant");
        EtudiantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtudiantMenuItemActionPerformed(evt);
            }
        });
        acceuilMenu.add(EtudiantMenuItem);

        participationMenuItem.setMnemonic('a');
        participationMenuItem.setText("participation");
        participationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participationMenuItemActionPerformed(evt);
            }
        });
        acceuilMenu.add(participationMenuItem);

        menuBar.add(acceuilMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("recherche");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Etudiant par TP");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        jMenuItem1.setText("Etudiant par nom");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem1);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nbtTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbtTPActionPerformed
        TPForm tf = new TPForm();
        desktopPane.add(tf);
        tf.setVisible(true);
    }//GEN-LAST:event_nbtTPActionPerformed

    private void EtudiantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtudiantMenuItemActionPerformed
        EtudiantForm es = new EtudiantForm();
        desktopPane.add(es);
        es.setVisible(true);
    }//GEN-LAST:event_EtudiantMenuItemActionPerformed

    private void participationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participationMenuItemActionPerformed
        ParticipationTpForm ps = new ParticipationTpForm();
        desktopPane.add(ps);
        ps.setVisible(true);
    }//GEN-LAST:event_participationMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        EtudiantByTP ebt = new EtudiantByTP();
        desktopPane.add(ebt);
        ebt.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        EtudiantByNom ebn = new EtudiantByNom(); // Vérifiez que ce n'est pas null
        desktopPane.add(ebn); // Assurez-vous que 'desktopPane' n'est pas null non plus
        ebn.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EtudiantMenuItem;
    private javax.swing.JMenu acceuilMenu;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem nbtTP;
    private javax.swing.JMenuItem participationMenuItem;
    // End of variables declaration//GEN-END:variables

}
